### ISSUE TITLE
Add support for Linux on s390x architecture (IBM Z/LinuxONE platform)

### ISSUE THREAD

**Issue by kulmannf** [IBM-Cloud/ibm-cloud-cli-release#113]
When I try to install the ibmcloud CLI on a server running on the s390x architecture I get the following error:
```
$ curl -sL https://clis.cloud.ibm.com/install/linux | bash
Unsupported Linux architecture: s390x. Quit installation.
```

but there seems to be already a version available on the location the script uses to download the binary: https://clis.cloud.ibm.com/download/bluemix-cli/latest/s390x

Besides that, it would be nice if plug-ins built for this platform would be supported as well.

**Comment by sandeep-at-ibm** [comment]
Can this support be made official, given the requirements for BYOI?

**Comment by ashleyrobertson** [comment]
Is someone able to take a look at this? Are there any plans for adding s390x support?

**Comment by quixote65** [comment]
This is also very important for my product team. we are being asked to provide s390x support and are needing ibmcloud and at the very least, container registry / container service plugin support on s390x. @rvennam - any thoughts on this that you can share?

**Comment by jinvanstee** [comment]
I'm working with a new to IBM Cloud client who will be driving the BYOI pattern from inside a IBM Cloud Hyper Protect Virtual Servers instance which is based on the s390x architecture. The only step that cannot be done there is the deploy step with `ibmcloud hpvs instance-create` because of the lack of this support. It has not come up as a hard requirement yet but I can see it becoming one with more clients coming onto the Hyper Protect family of offerings.

**Comment by djfitzgerald** [comment]
My zOS team just ran into this attempting to develop an internal prototype.  We think that we can build a manual workaround, but I want to add my voice to the chorus calling for this issue to be addressed.

**Comment by sandeep-at-ibm** [comment]
Little progress on this front. After a long discussion I think we have some traction for s390x support.
Tracking issue for the CLI Team: https://github.ibm.com/Bluemix/bluemix-cli/issues/3085

**Comment by dowem** [comment]
Hello @sandeep-at-ibm, I am the STSM for an Offering Management group in Z (focused on next-generation security products for Linux One and Linux-based offerings on zCX, z/VM and so on) and we have hit the issue that Jin and Dan have encountered and reported here. The mainframe is a major part of the hybrid cloud story (the defacto on-prem cloud for most of our fortune 500 clients).  Our team is developing a new set of offerings with HyperProtect which cannot work without the CLI working on z.  I have high hopes that the code core code works, as well as the plugins but this is a matter of support or just having system access to build the code on. Is the code built on s390 currently in your DevOps pipelines or is there a need for help somewhere to get this stuff supported and shipped?  Not being able to use our cloud CLI from our own architecture is jarring to explain to customers. Asking them to fall back to REST APIs makes the mainframe look harder to use than it should be. We cannot use many Hyper Protect integrations (a core part of the IBM Public cloud) because all Hyper Protect instances are z based. Similarly, we cannot streamline the z to Hyper Protect deployment model because there is no native CLI to provision cloud services from the Mainframe.  Please keep fighting the good fight to help make these tools support our clients and platform.

**Comment by sandeep-at-ibm** [comment]
Hi @dowem I am excited about all the work your team has in the pipeline. I'll add this to the justification I provided to the CLI team. I believe, this time around, we are going to be successful in getting official support for the CLI on s390x. Please stay tuned. I will have an update soon enough.

**Comment by 1scrooge** [comment]
@sandeep-at-ibm Hi. Do you have any news?

**Comment by sandeep-at-ibm** [comment]
@1scrooge I am waiting for feedback from the CLI Team. Will update you as soon as I hear back.

**Comment by sandeep-at-ibm** [comment]
@1scrooge @dowem 

Current status: 
- the s390x pipeline for Staging is ready
- the `tke` plugin has been added
- Waiting for `dbaas` and `hpvs` plugins to be added
- Waiting for publish to prod

If you have access to an s390x machine on the 9.x.x.x network, you can try it out by downloading the CLI/s390x from: https://clis.cloud.ibm.com/download/bluemix-cli/latest/s390x

**Comment by sandeep-at-ibm** [comment]
@1scrooge @dowem 

happy to report that tke plugin is now officially available on s390x. BIG Thanks to @Ross Heninger for toiling through the testing process. Now it will be much more easier for other plugins to be supported.

Here is what you can do on your s390x VMs (HPVS, zVPC, RHEL zLinux, etc):
curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash

ibmcloud plugin install https://plugins.cloud.ibm.com/downloads/bluemix-plugins/tke/1.1.4/tke-linux-s390x-1.1.4

ibmcloud login --sso

ibmcloud tke cryptounits (to query the crypto units provisioned in your account)

Stay tuned for other plugins to be supported as well

**Comment by davidhay1969** [comment]
Speaking personally, I'd also be keen to see the CS/KS plugin available for Linux on Z aka `s390x`

**Comment by sandeep-at-ibm** [comment]
@davidhay1969 I'll put that on my ToDo list

**Comment by steveclay** [comment]
I do not believe there is any more work for the CLI team to do here. Closing,

**Comment by sandeep-at-ibm** [comment]
thanks @steveclay for all your support in getting this far with `ibmcloud cli for s390x`.
From here on, it will be just adding support for plugins
