### ISSUE TITLE
Can't use podman with ibmcloud cr login

### ISSUE THREAD

**Issue by kgibm** [IBM-Cloud/ibm-cloud-cli-release#171]
If using `podman` and `docker` doesn't exist, then `ibmcloud cr login` fails:

```
$ ibmcloud cr login
FAILED
Could not locate 'docker'. Check your 'docker' installation and path.
```

A workaround is to create a symlink:

```
$ ln -s $(which podman) $(dirname $(which podman))/docker
$ ibmcloud cr login                                      
Logging in to 'icr.io'...
Logged in to 'icr.io'.

OK
```

Would be nice if `ibmcloud cr login` supported `podman`.

**Comment by jhart1685** [comment]
Further to my previous comment:
`ibmcloud cr login` is best thought of as a helper to perform `docker login` using credentials from your CLI session.
It is not required in order to use any of the other `cr` commands, and we document how to log in directly: https://cloud.ibm.com/docs/Registry?topic=Registry-registry_access 

The kind of improvement you may see with the command is detecting that docker is not installed, and linking you to new (and more useful) information about how to log in with various different clients.
It's probably not feasible or desirable to have the command try to detect various other clients and log you in using those, as the result would inevitably be quite brittle.
