### ISSUE TITLE
Cloud you please upgrade CF-CLI version for BMCLI as soon because CF-CLI defects fixed?

### ISSUE THREAD

**Issue by ShirleySunCN** [IBM-Cloud/ibm-cloud-cli-release#19]
## Defect Discription
['cf push' with non-english app name with no specific host, cf can't allocate a correct host ](https://github.com/cloudfoundry/cli/issues/1214)
#### Command  

cf push app 普通中文字符

#### What occurred

After I pushed it, I found that the app route is wrong.
It can't allocate a correct host and correct route for me.
And I click this route, the app can't start successfully.

#### What you expected to occur
I expect that when I push an app with non-english name, 'cf' should allocate a correct route for me, and the app can start succesfully.

## Defect fixed in cf CLI 6.34.0
![image](https://user-images.githubusercontent.com/31336898/35212480-42767f4e-ff95-11e7-9939-d67465e08cdc.png)

## BMCLI version
download from [https://clis.ng.bluemix.net/download/bluemix-cli/latest/osx](https://clis.ng.bluemix.net/download/bluemix-cli/latest/osx)
```
shirleydembp:~ shirley$ export LANG=en_US.UTF-8
shirleydembp:~ shirley$ bx -v
bx version 0.6.4+41cb1aa9-2017-12-19T04:00:09+00:00
shirleydembp:~ shirley$ bx cf -v
Invoking 'cf -v'...
cf version 6.32.0+0191c33d9.2017-09-26
shirleydembp:~ shirley$ 
```

**Comment by archerzz** [comment]
@ShirleySunCN 

In CF CLI 6.34.0 there is a big change in `push` implementation (see [changelog](https://github.com/cloudfoundry/cli/releases/tag/v6.34.0)). So we need more time to investigate and triage. Using Chinese characters as hostname is technically feasible since a couple of year ago, but it's not a popular choice now. I'll set this issue a low priority. However, we'll upgrade CF CLI regularly, so soon or later this issue will be fixed. Thanks for your issue and I hope you could understand.

**Comment by archerzz** [comment]
@ShirleySunCN We've upgraded the embedded CF CLI to 6.34.1. Please download IBM Cloud CLI `0.6.7`. Thanks
