### ISSUE TITLE
kubectl cluster token expires

### ISSUE THREAD

**Issue by sdaschner** [IBM-Cloud/ibm-cloud-cli-release#77]
After successfully connecting to a cluster and after a few days (?) the `kubectl` complains that the refresh token expired. Why are developers forced to re-authenticate against their cluster? This adds additional burden to the developer experience.

Output
```json
{                                        
  "context": {
    "requestId": "...",
    "requestType": "incoming.Identity_Token",
    "userAgent": "Go-http-client/2.0",
    "clientIp": "216.46.28.66",
    "url": "https://iam-id-1.ng.bluemix.net",
    "instanceId": "iamid-3.8-5262-...",
    "threadId": "69aada",
    "host": "iamid-3.8-5262-...",
    "startTime": "13.03.2019 14:32:49:427 UTC",
    "endTime": "13.03.2019 14:32:49:428 UTC",
    "elapsedTime": "1",
    "locale": "en_US",
    "clusterName": "iam-id-prdal10-ljdb"
  },
  "errorCode": "BXNIM0408E",
  "errorMessage": "Provided refresh token is expired"
}
```

**Comment by archerzz** [comment]
@sdaschner This is by design. As the error message indicates, `Provided refresh token is expired`. According to OAuth 2 spec, the refresh token can be used to generate new access token. But refresh token itself also has expiry. I'm not sure how long `a few  days` is, but it's clear that you haven't used the `kubectl` for quite a long time so that both access token and refresh token expired.

**Comment by sdaschner** [comment]
I see your point but, TBH I don't really understand the reasoning why the token expires that soon / at all. The behavior of GKE clusters in comparison, e.g. is that they don't need re-authentication (at all or at least not within multiple months).

So I'm suggesting to change the expiration behavior of the CLI tokens in general.

**Comment by dcberg** [comment]
The API token expires in 1 hour but the refresh token I believe expires after about a month (definitely longer than a few days). IKS cannot control the expiration of the refresh token. This is controlled by IAM. If we had a non-expiring refresh token then we could provide an experience where it appears that the access never expires. This would need to be a change in IAM.

For GKE they must either have a non-expiring API toke (seems like a bad idea) or a non-expiring refresh token.

**Comment by sdaschner** [comment]
Got it, thanks for the explanation.

Can we set the expiration of the API token to a more sensible default than 1 hour? I'd expect that users can use the API for definitely a longer time. The current (login) usability gets in the way too quickly.

I wouldn't even agree that a (per default) non-expiring token is such a bad idea but that's up to discussion, I guess. We definitely want to clarify the behavior and document how to create a token for (technical) users / automation that don't expire.

**Comment by archerzz** [comment]
@sdaschner you need to ask IAM team to tune the expiry. We don't have control of any token. They are all generated by backend, and we cannot change them on our side. You can contact Martin Smolny.

**Comment by boyang9527** [comment]
@sdaschner  This is a new feature request to IAM, so let us  move the issue over there.

**Comment by sdaschner** [comment]
@boyang9527 How can I create a feature request in IAM?

(TBH, I would even argue this is more a bug, looking at a developer / user experience angle)

**Comment by sdaschner** [comment]
@boyang9527 @dcberg How can I create a feature request in "IAM"?

**Comment by romeokienzler** [comment]
@archerzz I have the same problem - it seems the issue got closed without a feature request being created / referenced here. Can you please shine some light on the progress? It is in fact very tedious and even breaking some use cases if the token expires (after approx. 1 day or less fyi).

**Comment by zholz** [comment]
Same for me, 3-7 days and my refresh tocken is done. Tilting me a lot.

**Comment by neilramaswamy** [comment]
This was happening to me as well, but I think it had to due with the fact that I was trying to connect to a cluster to which I no longer had access (i.e. connecting to a cluster that had since been deleted). 

After running `ibmcloud ks cluster config --cluster <cluster_name>` with the _right_ cluster, the issue resolved itself. I'm not sure if that's entirely related to what's going on in this thread, but perhaps this will help someone who stumbles upon this thread from a search engine. Also, it seems as if the error message of "BXNIM0408E" is a bit too broadly applied, since trying to talk to a deleted cluster really shouldn't result in an error message about refresh tokens being expired.
